### ISSUE TITLE
Typescript declaration files

### ISSUE THREAD

**Issue by lordlycastle** [Originate/chai-match-pattern#10]
Hiya, this is an awesome plugin and I don't think there is another similar plugin. It would greatly benefit from Typescript declaration files so it can also be used in TS projects. 

Recent polls say TS is preferred by ~60% of the programmers. They can be submitted to the [DefinitelyTyped](https://definitelytyped.org/)!

**Comment by daniel-kneip** [comment]
Hi! I just created a pull request for DefinitelyTyped here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65898 😄

**Comment by daniel-kneip** [comment]
@lordlycastle The PR has been merged and I was able to `npm i -D @types/chai-match-pattern` 👍🏻

**Comment by lordlycastle** [comment]
Thank you!
